version: '3'
services:
  myapplication:
    build: ./configs-server
    environment: 
      - MONGO_USER=mongo
      - MONGO_PASSWORD=password
      - MONGO_HOST=mongodb
    ports:
      - 8080:8080
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=password
